import Link from 'next/link';
import {FiArrowUpRight} from 'react-icons/fi';
import Banner from '../components/Banner';
import SEO from '../components/SEO';
import ProjectGallery from '../components/ProjectGallery';
import Experience from '../components/Experience';
import ContactSection from '../components/ContactSection';
import {about,expertise,tools} from '../data/portfolioData';
export default function Home(){return <><SEO/><main id="main"><Banner/><section className="intro-strip"><div className="container intro-inner"><p className="eyebrow">THE DESIGNER BEHIND THE WORK</p><div><h2>{about.short}</h2><p>{about.intro}</p><Link className="text-link" href="/about">A little more about me <FiArrowUpRight/></Link></div></div></section><section id="work" className="container section"><div className="section-heading"><div><p className="eyebrow">01 / THE PORTFOLIO</p><h2>Selected <em>work.</em></h2></div><p>A selection of visual design, advertising,<br/>editorial and creative concept work.</p></div><ProjectGallery/></section><section className="expertise-section"><div className="container section"><div className="section-heading"><div><p className="eyebrow">02 / WHAT I BRING</p><h2>Creative <em>expertise.</em></h2></div><p>From the first spark of an idea<br/>to the final visual detail.</p></div><div className="expertise-grid">{expertise.map(([title,description],i)=><article key={title}><span className="index-number">0{i+1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section><section className="container section"><div className="section-heading"><div><p className="eyebrow">03 / THE JOURNEY</p><h2>Creative <em>experience.</em></h2></div><Link href="/about#experience" className="text-link">Explore my journey <FiArrowUpRight/></Link></div><Experience compact/><div className="tools-strip"><span className="eyebrow">MY CREATIVE TOOLKIT</span>{tools.map(tool=><span key={tool}>{tool}</span>)}</div></section><ContactSection/></main></>;}
